nodes:
  hosts:
    m-node-1:
      ansible_host: 172.10.10.201
      ansible_user: iamslave
      ans_host_add: 172.10.10.201
      server_id: 1
    m-node-2:
      ansible_host: 172.10.10.202
      ansible_user: iamnode3
      ans_host_add: 172.10.10.202
      server_id: 2
    m-node-3:
      ansible_host: 172.10.10.203
      ansible_user: iam-m-node-3
      ans_host_add: 172.10.10.203
      server_id: 3

