---
# Copy cluster.cnf file to all nodes
- name: Copy Galera config
  template:
      src: cluster.cnf.j2
      dest: /etc/mysql/conf.d/galera.cnf
      owner: root
      mode: 0644
      force: no

# Check for Galera idempotency
- name: Check for Galera idempotency
  command: /usr/bin/mysql -u root -e "SHOW STATUS LIKE 'wsrep_cluster_size'"
  register: gal_stat_str
  when: ansible_default_ipv4.address == groups['nodes'][0]

- set_fact:
    galera_stat: "{{ gal_stat_str.stdout.split('\t').2 }}"
  when: galera_stat is defined

# Stop MariaDB on all nodes
- name: Stop MariaDB on all nodes
  service: name=mariadb state=stopped

# Bootstrap first MariaDB Galera cluster node
- name: Bootstrap first MariaDB Galera cluster node
  command: galera_new_cluster
  when: 
    - ansible_default_ipv4.address == groups['nodes'][0]
    - galera_stat == '0'

# Start MariaDB on all nodes
- name: Start MariaDB on all nodes
  service: name=mariadb state=started

