- name: Install MariaDB
  apt:
    name: mariadb-server
    state: present
    update_cache: true

- name: Copy my.cnf file
  template:
    src: my.cnf.j2
    dest: "/etc/mysql/my.cnf"
  notify: Restart MariaDB

- name: Ensure MariaDB is running
  service:
    name: mysql
    state: started
    enabled: true

- name: Wait for MariaDB to start
  wait_for:
    port: 3306

